const urlSearchParams = new URLSearchParams(location.search)
const form = document.createElement('form')
form.setAttribute('method', 'post')
form.setAttribute('action', urlSearchParams.get('action'))
new Array(...urlSearchParams).forEach(([key, value]) => {
  console.log(key, value)
  const hiddenField = document.createElement('input')
  hiddenField.setAttribute('type', 'hidden')
  hiddenField.setAttribute('name', key)
  hiddenField.setAttribute('value', value)
  form.appendChild(hiddenField)
})
document.body.appendChild(form)
form.submit()
